### ISSUE TITLE
Kring kopiëren?

### ISSUE THREAD

**Issue by gertst** [igoethal/eendraadschema#1]
Beste,

Is het mogelijk om een kring te copy/pasten zodat je (bijna) gelijkaardige kringen niet opnieuw hoeft te maken? Dat lijkt me een fundamenteel feature - ik kijk er dus wslk over? - maar ik vind het niet terug ...

Bedankt!

Gert

**Comment by igoethal** [comment]
Beste Gert,

Goed punt. Op dit moment is dat niet mogelijk (enkel verplaatsen), maar kan uiteraard wel geïmplementeerd worden.
Ik zet hem op de backlog.

Groeten,

Ivan

**Comment by gertst** [comment]
Dag Ivan,

Ik heb ondertussen je code geforked om zelf een kijkje te nemen- misschien kan ik dit zelf wel toevoegen. Ik bekijk het even en als het snel lukt, bezorg ik je mijn code via een pull request ;)

Het idee: Bij elke ElectroItem node komt er een knop "Copy" en een knop "Paste" bij. Als je dan paste vervang je de inhoud van de huidige node met deze in de copy.
Wat denk je?

**Comment by igoethal** [comment]
Beste Gert,
Ik heb het ondertussen geimplementeerd.
Ik dacht ook dat het eenvoudig zou zijn maar toch een uurtje aan bezig gweest.
Er waren met name twee complicaties:
- Je wil uiteraard een echte kopie van het object zelf en niet gewoon een copy van de pointer
- Telkens je een element toevoegt aan het schema wordt de onderliggende array opnieuw gesorteerd, dus als je in een lus elk onderliggend element gaat kopieren dan verandert de array terwijl je er doorheen aan het lopen bent, en dat is niet zo handig :) Een nieuwe versie is ondertussen opgeladen op Github en op de website. Je kiest bovenaan "Verplaatsen/Clone" in plaats van invoegen en kan dan een dubbel maken van eender welk element (met knop "Clone" en dat eender waar naartoe slepen).

Groeten,
Ivan

**Comment by gertst** [comment]
Haha, je bent me te vlug af! Maar wat doet men anders op een corona-zondag, dan wat in code duiken? :-P
Bedankt voor de heel snelle update en voor je handige tool!

Gr,
Gert

**Comment by igoethal** [comment]
Sure thing, neemt niet weg dat als je ooit iets wil aanpassen dit uiteraard
zeker welkom is.

Onderschat echter de complexiteit van de code niet. Zoals dat doorgaans
gaat begint zoiets klein en groeit het uit tot een behoorlijk complex
geheel.

Aanpassingen van individuele Electro items zijn redelijk te doen, als het
over aanpassingen in de hiërarchische structuur zelf gaat is de learning
curve behoorlijk hoog vrees ik.
