### ISSUE TITLE
Aftakdozen en aansluit punten beperkt tot 1 kind

### ISSUE THREAD

**Issue by oliv3r** [igoethal/eendraadschema#6]
Hey @igoethal 

super bedankt voor dit project. was al tijden hierna op zoek!

Ondanks dat een eendraadschema in Nederland niet verplicht is, vind ik het een heel goed idee en wil dit graag in mijn meterkast hebben :)

Nu is het bij ons in Nederland gebruikelijk om vanuit de automaat een kabel te trekken naar een centraal punt, meestal is dat aan het plafond, de algemene 'aftakdoos'. Vanaf hier, zoals de naam het al zegt, takken we dan af naar een X aantal stopcontacten (of lege trek-dozen). Aan de afak doos hangt vaak ook de centrale lamp, met draden na een schakelaar met of zonder een stopcontact.

Echter, is het op dit moment niet mogelijk om een aftakdoos of inbouwdoos meerdere kinderen toe te voegen dan 1. Ik snap dat dit een stuk moelijker te renderen is, maar zou wel mogelijk moeten zijn?

Ook zie ik dat met stopcontacten. Als ik graag de vebruikers aan het stopcontact zou willen modeleren, kan dit nu niet (b.v. wasmachine die aan het stopcontact hangt.

Het zelfde probleem denk ik is ook met een dubbele schakelaar, daar zouden toch 2 lampen aan moeten hangen. (Trouwens je mist ook de dubbele schakkelaar, 1 maar enkel polig een maal dubbel polig. E.g. een dubbele schakelaar met een directe lamp en 1x een kruis schekalaar. Denk aan de hal beneden, met een knop voor de hal, en een 2de schakelaar voor de lamp boven, die ook een schakelaar boven heeft, maar dat is misschien zijn eigen issue ;p)

(P.s. overigens geld dit blijkbaar ook voor omvormers, terwijl een omvormer meerdere strings aan kan)

Kan dit nu wel 'faken' door een ongelabelde kring te plaatsen, al ziet dat met b.v. stopcontacten weer vreemd uit.
![image](https://user-images.githubusercontent.com/1245341/205145887-b00ce0a4-7e1e-4718-a763-5774ede14282.png)
dit bedoel ik!

edit: Ik lees trouwens wel in de handleiding dat dit waarschijnlijk de bedoeling was?

**Comment by igoethal** [comment]
Beste Oliv3r,

Door achter een aftakdoos het element "splitsing" te gebruiken kan je wellicht wel benaderen wat jij probeert te tekenen:

![image](https://user-images.githubusercontent.com/66268237/205510868-834ddb9b-ab7f-458b-8a74-0c635709ee55.png)

Verbruikers kan je volgens mij wel gewoon achter een stopcontact hangen. Let wel, in België wordt dit vaak bewust niet gedaan want eens bij ons een schema gekeurd werd kan je het niet meer kosteloos wijzigen.  We gaan doorgaans dus niets op een schema vermelden dat niet strikt noodzakelijk is zodat achteraf nog de nodige vrijheid blijft om de zaken die er niet op staan aan te passen.

![image](https://user-images.githubusercontent.com/66268237/205511222-8772a5f9-36bb-4a1f-ac7b-08a71d222cfc.png)

Wat een dubbele schakelaar betreft (twee schakelaars achter 1 plaatje) is het in België gebruikelijk om die als twee aparte schakelaars in het schema te verwerken. Eventueel zetten we er dan in het onderschrift bij dat beide schakelaars achter hetzelfde plaatje zitten maar meestal doen we zelf dat niet.  Soms is één van beide schakelaars op zichzelf weer onderdeel van een wisselschakeling en als dat allemaal op 1 enkele lijn in het schema moet wordt het al heel snel erg complex.  Dus gewoon tekenen alsof het twee afzonderlijke schakelaars zijn.

Qua zonnepanelen zou ik het inderdaad doen zoals jij suggereert.

Met vriendelijke groeten,

Ivan
