### ISSUE TITLE
Drukknoppen bij een minuterie

### ISSUE THREAD

**Issue by roelderickx** [igoethal/eendraadschema#7]
Ik probeer een minuterie toe toe voegen met 2 drukknoppen en 1 lamp. In inkscape heb ik het even geschetst en wat ik zou moeten bekomen is dit ongeveer (5 is het kringnummer):
![image](https://user-images.githubusercontent.com/33570192/205504063-2299562e-4d4f-4bc4-a91a-379107d00eec.png)

Dat lukt me niet met deze toepassing, maar mogelijk zie ik iets over het hoofd.
- Ofwel voeg ik een lichtcircuit toe, stel het schakelaartype in op minuterie en heb de kans om een aantal lichtpunten in te geven. Maar ik kan geen drukknoppen toevoegen, noch een niveau eronder toevoegen om daar de drukknoppen toe te voegen.
- Ofwel voeg ik een schakelaar van het type minuterie toe, maar dan kan ik slechts 1 niveau eronder aanmaken voor ofwel de lichtpunten ofwel de drukknoppen. Ik heb ze allebei nodig.

Op zich heb ik geen probleem om het zoals in de tweede optie in te geven. Dan volstaat het dus om toe te laten dat een minuterie 2 kind-niveaus kan hebben ipv 1. Een andere oplossing is om toch een kindniveau toe te laten voor een lichtcircuit met een minuterie. Of beide, dan heb je maximale flexibiliteit :-)
Het aantal drukknoppen als parameter bij een lichtcircuit toevoegen kan ook, enkel in geval van minuterie dan. Maar dan moet je wel alle opties van de drukknoppen ook mee overnemen (verklikkerlicht / halfwaterdicht / ...). Dat lijkt me op het eerste zicht wat overkill.

**Comment by igoethal** [comment]
Als de drukknoppen op 230V werken zou ik dit als volgt tekenen:

![image](https://user-images.githubusercontent.com/66268237/205511398-9e948117-7996-4795-83d1-60c657f2782d.png)

Het is niet 100% correct omdat in realiteit de zaken niet in serie staan maar de bedoeling is wel duidelijk dus ik verwacht niet dat dit niet aanvaard gaat worden bij een keuring.

Als de drukknoppen op laagspanning werken zou ik ze gewoon weglaten uit het schema.  In principe moeten de laagspanning onderdelen niet gekeurd worden. Dit heeft ook het voordeel dat je later nog een knop kan toevoegen zonder alles opnieuw te moeten laten keuren.

Als je het toch iets correcter wil tekenen zie ik volgende twee mogelijkheden:

![image](https://user-images.githubusercontent.com/66268237/205511539-fb6c851f-ee0f-4f9e-b37b-ccf21649f65f.png)

![image](https://user-images.githubusercontent.com/66268237/205511592-d53125de-f7d9-4103-9cd6-cf908d71dbfc.png)

**Comment by roelderickx** [comment]
Ok bedankt. Ik denk dat alle 3 de opties acceptabel zijn, ik koos na wat afweging voor de minuterie icm een splitsing.
